add sentio to tooling documentations
Consensys/doc.zk-evm pull request #250
Opened 2023-08-08 15:42 UTC by qiaokan

Hi,
  This is Kan from sentio.xyz. adding sentio to the tooling documentation.

2023-08-09 12:40 UTC, emilyJLin95 requested changes
hihi!

Can you delete the `yarn.lock` file - is it necessary?

Also, your build is failing I think because of a missing tag
Is it building locally for you? you can find instructions here: https://docs-template.consensys.net/contribute/preview

2023-08-09 12:40 UTC, emilyJLin95 commented on docs/build-on-linea/tooling/data-indexers/sentio.md
> +<figure><img src="https://github.com/sentioxyz/docs/blob/main/.gitbook/assets/all.gif" alt=""></figure>
there's no closing tag for `img`

2023-08-09 15:55 UTC, qiaokan commented
> hihi!
> 
> Can you delete the `yarn.lock` file - is it necessary?
> 
> Also, your build is failing I think because of a missing tag Is it building locally for you? you can find instructions here: https://docs-template.consensys.net/contribute/preview

Thanks for the review!
yes. removed yarn.lock.
i am able to build/run it locally.

2023-08-10 13:47 UTC, emilyJLin95 approved these changes
LGTM

2023-08-10 13:47 UTC, merged