300 doc pado
Consensys/doc.zk-evm pull request #301
Opened 2023-09-22 14:01 UTC by xiafubiao

Add PADO to doc/tooling and infrastructure/attestation, with a created new category "Attestation", fixes #300

2023-09-28 14:47 UTC, emilyJLin95 requested changes
Hi can you remove the package-lock.json change?

Can you also run `npm run lint` and edit `project-words.txt` to allowlist new words

Also just `npm run build` to make sure everything is building correctly?

2023-10-18 19:16 UTC, emilyJLin95 approved these changes
Can you add these words the `project-words.txt` and run `npm lint` to make sure the lint passes

/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:2:8 - Unknown word (PADO)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:5:4 - Unknown word (PADO)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:7:2 - Unknown word (PADO)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:7:124 - Unknown word (PADO)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:9:29 - Unknown word (PADO)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:21:110 - Unknown word (PADO's)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:26:54 - Unknown word (Verax)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/attestations/PADO.md:26:283 - Unknown word (Verax)

2023-10-19 04:16 UTC, closed without merging

2023-10-19 04:18 UTC, xiafubiao commented
I created a new PR in the [new link](https://github.com/Consensys/doc.zk-evm/pull/328)

2023-10-19 04:21 UTC, xiafubiao commented on package-lock.json
Hey Emily, thx for the review, I fixed the issues (the package-lock.json issue, and the lint pass issue) and have now created a new PR in another [thread](https://github.com/Consensys/doc.zk-evm/pull/328). sorry for the late reply due to the holidays