Adding Cookie3 to tooling folder
Consensys/doc.zk-evm pull request #333
Opened 2023-10-23 14:07 UTC by a-boruszak

As a new member of Linea ecosystem, we'd like to add Cookie3 docs into tooling folder.

2023-10-23 14:13 UTC, emilyJLin95 commented on docs/build-on-linea/tooling/analytics/_category_.json
Is this file supposed to be empty?

Or
```
{
  "label": "Analytics"
}
``

2023-10-23 14:13 UTC, emilyJLin95 commented on docs/build-on-linea/tooling/analytics/_category_.json
Is this file supposed to be empty?

Or
```
{
  "label": "Analytics"
}
``

2023-10-23 14:13 UTC, emilyJLin95 commented on docs/build-on-linea/tooling/analytics/_category_.json
Is this file supposed to be empty?

Or
```
{
  "label": "Analytics"
}
``

2023-10-23 14:13 UTC, emilyJLin95 requested changes
Left one comment!

2023-10-23 14:31 UTC, emilyJLin95 commented on docs/build-on-linea/tooling/analytics/cookie3.md
> +##Benefits of using Cookie3
does this need a space here?

2023-10-23 14:43 UTC, a-boruszak commented on docs/build-on-linea/tooling/analytics/cookie3.md
> +##Benefits of using Cookie3
Do you mean space between # and line 3?

2023-11-29 19:11 UTC, emilyJLin95 approved these changes
LGTM

2023-11-29 19:12 UTC, merged