Deep Dive Edits: Account Abstraction section, other minor fixes
Consensys/doc.zk-evm pull request #420
Opened 2024-02-13 13:25 UTC by mapachurro

If you want a  closer look at what this PR includes, I tried to be granular in my commits.

I did at one point mention "attestations" in a commit -- I meant "account abstraction".

2024-02-14 10:37 UTC, jlwllmr requested changes
Mostly fine but left a few comments. Mainly we need to pick whether we want headings to start with `##` or `#`.

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/gas-fees.mdx
Text for some of the bullets seems to be spread across multiple line, I think because the author has used line breaks — something which I think we should generally avoid. It doesn't seem to impact how it actually renders when live, but probably something to correct in future. 

If it's to make sure all `.mdx` text is visible in the code editor while working (understandable), then we should really just be adjusting VS Code settings to enable text wrapping rather than adding line breaks.

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/account-abstraction.mdx
Why are the bulleted lists placed within quote blocks?

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/account-abstraction.mdx
> +> - Account Recovery ("social recovery", recovery via email or other identities / accounts)
```suggestion
> - Account Recovery ("social recovery", recovery via email or other identities/accounts)
```

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/account-abstraction.mdx
Not sure account abstraction needs to be capitalised — I instinctively wouldn't, but open to counter arguments. (Additionally, not sure we need to print it as "`Account Abstraction`" in line 5.

FWIW, the [ERC-4437 proposal](https://eips.ethereum.org/EIPS/eip-4337) doesn't capitalise and neither do [other Consensys publications](https://metamask.io/news/latest/account-abstraction-past-present-future/).

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/noves.md
Not sure about this — in the other pages in this section you ensured the headings started at `h1` (`#`) and removed hashes; the edits here deliberately add them.

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/pimlico.md
Same as before; this seems inconsistent with the approach elsewhere, where you made sure we started with `h1`. Looking elsewhere on this page as well, there seems to be quite erratic capitalisation: "Smart Accounts" (are we using sentence case here or what?), "Paymaster", "Single Entry Point Contact", etc.

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/smartwallets.md
By this point, you know what I'm going to say... headings are inconsistent within this section. We need to pick whether we start with `h1` or `h2`, and then apply it across the board. (And ideally across the rest of the docs as well.)

2024-02-14 10:37 UTC, jlwllmr commented on docs/build-on-linea/tooling/account-abstraction/station.md
again here.

2024-02-15 18:56 UTC, mapachurro commented on docs/build-on-linea/tooling/account-abstraction/smartwallets.md
STANDARDS

2024-02-16 14:33 UTC, mapachurro commented on docs/build-on-linea/gas-fees.mdx
I'll leave that as-is for now, but a good point to document--perhaps in the `Linea Docs Review` doc.

2024-02-16 14:37 UTC, mapachurro commented on docs/build-on-linea/tooling/account-abstraction/account-abstraction.mdx
Meh, I thought it looked better, but it's fine, I'll remove it for the sake of consistency.

2024-02-16 14:38 UTC, mapachurro commented on docs/build-on-linea/tooling/account-abstraction/account-abstraction.mdx
Oh hell yes, thank you for this

2024-02-16 14:45 UTC, mapachurro commented on docs/build-on-linea/tooling/account-abstraction/pimlico.md
Thanks for catching those. _for the record etc_ I didn't write this ;-P

2024-02-16 14:46 UTC, mapachurro commented on docs/build-on-linea/tooling/account-abstraction/smartwallets.md
I adjusted this one a bit, but I think that my suggestion earlier makes sense as a standard:

- start with h2, so that the title of the page is visible
- yeah.
![image](https://github.com/Consensys/doc.zk-evm/assets/7252642/085b2b1f-1720-4304-8d30-a5b1cf0db0c6)

2024-02-16 16:34 UTC, jlwllmr approved these changes

2024-02-16 16:34 UTC, merged