Add instructions to run a node on Sepolia
Consensys/doc.zk-evm pull request #475
Opened 2024-03-14 00:12 UTC by bgravenorst

Add instructions to run a node on Sepolia

2024-03-22 10:03 UTC, jlwllmr requested changes
LGTM, other than one suggestion about improving the precision of the tab labels

2024-03-22 10:03 UTC, jlwllmr commented on docs/build-on-linea/run-a-node/use-binary.mdx
I'd recommend we update the tabs to "Linea Sepolia", "Linea Goerli" etc. rather than just "Sepolia", "Goerli" — although it's clear from the context what networks we're referring to. Reached this conclusion in discussion with @Ludcour et al. Also aligns with the proposed usage in #489.

2024-03-26 06:29 UTC, bgravenorst commented
@jlwllmr, let me know if you're happy with those changes.

2024-03-26 11:00 UTC, jlwllmr approved these changes

2024-03-27 15:36 UTC, merged