Mobula
Consensys/doc.zk-evm pull request #520
Opened 2024-04-03 14:43 UTC by xyeuu

Add Mobula to "Tooling and infrastructure"

2024-04-10 10:16 UTC, jlwllmr requested changes
Thanks for the submission — I've left a few comments, mostly just to apply house style (sentence case for titles) and remove some capitalisation. 

Generally: could you take a stab at toning down the marketing-language style that these pages use? It's inappropriate to the docs page — we want to describe, rather than sell. I left a few comments referring to examples, so hopefully the request is clear enough.

Thank you and let me know if anything is unclear.

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/analytics/mobula.md
> +By transforming complex datasets into clear, actionable insights, this platform aids in streamlining decision-making across various contexts. It empowers users to uncover opportunities and tackle cha
The last sentence here strays too far into superlatives/marketing language — could you soften?

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/analytics/mobula.md
> +- **[Dive into our Documentation](https://docs.mobula.io)** - Delve into the extensive resources of [Mobula’s](https://docs.mobula.io) documentation. From detailed API guidelines to all-encompassing
```suggestion
- **[Dive into our documentation](https://docs.mobula.io)** - Delve into the extensive resources of [Mobula’s](https://docs.mobula.io) documentation. From detailed API guidelines to all-encompassing tutorials, our documentation is designed to empower users across all levels. 
```

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/analytics/mobula.md
> +- **[Explore Mobula App](https://mobula.io)** - Access the heart of cryptocurrency analytics with the [Mobula](https://mobula.io) app. Designed for ease of integration and enriched with powerful data
```suggestion
- **[Explore the Mobula app](https://mobula.io)** - Access the heart of cryptocurrency analytics with the [Mobula](https://mobula.io) app. Designed for ease of integration and enriched with powerful data insights, our app provides the tools you need to navigate the crypto market confidently. Get started today and harness the potential of advanced analytics tailored for your success.
```

Again, last sentence here is too marketing-oriented for the docs page. Either remove or soften please

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/analytics/mobula.md
> +- **[Dive into our Documentation](https://docs.mobula.io)** - Delve into the extensive resources of [Mobula’s](https://docs.mobula.io) documentation. From detailed API guidelines to all-encompassing
Removed last sentence as it's too marketing-like; feel free to re-add if you rephrase.

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/data-indexers/mobula.md
> +[Mobula](https://docs.mobula.io) is a sophisticated Data Layer that offers Octoflow, a powerful system designed to stream any on-chain action, including events, traces, transactions, and blocks. This
```suggestion
[Mobula](https://docs.mobula.io) is a sophisticated data layer that offers Octoflow, a powerful system designed to stream any on-chain action, including events, traces, transactions, and blocks. This provision enables unparalleled access and analytics, equipping users with precise insights for informed decision-making. With Octoflow, [Mobula](https://docs.mobula.io) redefines how data-driven strategies are developed, making it an indispensable asset for in-depth blockchain analysis.
```

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/data-indexers/mobula.md
> +Create a room with Mobula core team **[Here](https://t.me/MobulaPartnerBot?start=Linea_Docs_Octoflow)**
```suggestion
Create a room with Mobula core team **[here](https://t.me/MobulaPartnerBot?start=Linea_Docs_Octoflow)**.
```

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/data-indexers/mobula.md
> +- **[Dive into our Documentation](https://docs.mobula.io)** - Delve into the extensive resources of [Mobula’s](https://docs.mobula.io) documentation. From detailed API guidelines to all-encompassing
```suggestion
- **[Dive into our documentation](https://docs.mobula.io)** - Delve into the extensive resources of [Mobula’s](https://docs.mobula.io) documentation. From detailed API guidelines to all-encompassing tutorials, our documentation is designed to empower users across all levels. Whether you're looking to integrate [Mobula's](https://docs.mobula.io) features into your application or eager to explore the full scope of functionalities we offer, you'll find everything required to unlock the full potential of your data-driven initiatives.
```

2024-04-10 10:16 UTC, jlwllmr commented on docs/build-on-linea/tooling/data-indexers/mobula.md
> +- **[Explore Mobula App](https://mobula.io)** - Access the heart of cryptocurrency analytics with the [Mobula](https://mobula.io) app. Designed for ease of integration and enriched with powerful data
```suggestion
- **[Explore the Mobula app](https://mobula.io)** - Access the heart of cryptocurrency analytics with the [Mobula](https://mobula.io) app. Designed for ease of integration and enriched with powerful data insights, our app provides the tools you need to navigate the crypto market confidently. Get started today and harness the potential of advanced analytics tailored for your success.
```

2024-04-10 10:17 UTC, jlwllmr commented
@xyeuu could you also update `project-words.txt` with `Mobula`, `Mobula's`, and `Octoflow` and `Octoflow's`? See the spelling linter for more info.

2024-04-10 17:19 UTC, xyeuu reviewed
I've tried to make the content more informative, please let me know if I need to go over it again.

2024-04-11 08:31 UTC, jlwllmr approved these changes
LGTM, thanks for your work on this

2024-04-11 08:31 UTC, merged